[package]
name = "dispatch-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dispatch"
path = "src/main.rs"

[dependencies]
crudkit-core = { path = "../crudkit/crudkit-core", default-features = false }
clap = { version = "4", default-features = false, features = ["color", "derive", "error-context", "help", "std", "suggestions", "usage"] }
dispatch-api-client = { path = "../dispatch-api-client", default-features = false }
dispatch-types = { path = "../dispatch-types", default-features = false }
rootcause = { version = "0.13.0", default-features = false }
serde = { version = "1", default-features = false, features = ["std"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
tabled = { version = "0.20.0", default-features = false, features = ["std", "derive"] }
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread", "time"] }
uuid = { version = "1.19", default-features = false, features = ["v4"] }

[dev-dependencies]
assertr = { version = "0.6.0", default-features = false, features = ["std"] }
