[package]
name = "dispatch-types"
version = "0.1.0"
edition = "2024"

[dependencies]
crudkit-core = { path = "../crudkit/crudkit-core", default-features = false }
serde = { version = "1", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1", default-features = false, features = ["std"] }

[dev-dependencies]
assertr = { version = "0.6.0", default-features = false, features = ["std"] }
