[package]
name = "dispatch-api-client"
version = "0.1.0"
edition = "2024"

[dependencies]
dispatch-types = { path = "../dispatch-types", default-features = false }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", default-features = false, features = ["std"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
urlencoding = { version = "2", default-features = false }

[dev-dependencies]
assertr = { version = "0.6.0", default-features = false, features = ["std"] }
