use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_query::{Asterisk, Func, SimpleExpr, TableCreateStatement};

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260905_000051_add_knowledge_evidence_proposals"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // PostgreSQL requires referenced composite keys to exist before child-table
        // construction. These portable parent identities also prevent cross-cycle binding.
        for (name, table, columns) in [
            (
                "uq_inventory_bootstrap_binding",
                "knowledge_inventory_manifests",
                vec![
                    "project_id",
                    "cycle_id",
                    "id",
                    "shard_id",
                    "acquisition_id",
                    "fence",
                    "attempt",
                    "source_snapshot_id",
                    "uninitialized_knowledge_sha256",
                ],
            ),
            (
                "uq_cycle_run_submission_guard",
                "knowledge_cycle_run_bindings",
                vec![
                    "project_id",
                    "cycle_id",
                    "run_id",
                    "computation_sha256",
                    "acquisition_id",
                    "fence",
                    "attempt",
                ],
            ),
            (
                "uq_cycle_run_packet_guard",
                "knowledge_cycle_run_bindings",
                vec![
                    "project_id",
                    "cycle_id",
                    "run_id",
                    "shard_id",
                    "stable_shard_sha256",
                    "computation_sha256",
                    "acquisition_id",
                    "fence",
                    "attempt",
                ],
            ),
            (
                "uq_inventory_evidence_input",
                "knowledge_inventory_manifests",
                vec!["project_id", "cycle_id", "id", "source_snapshot_id"],
            ),
        ] {
            let mut index = Index::create();
            index.name(name).table(Alias::new(table)).unique();
            for column in columns {
                index.col(Alias::new(column));
            }
            manager
                .create_index(index.if_not_exists().to_owned())
                .await?;
        }
        for table in knowledge_evidence_proposal_tables() {
            manager.create_table(table).await?;
        }
        for (name, table, columns) in [
            (
                "uq_knowledge_bootstrap_scope_semantic",
                "knowledge_bootstrap_scope_cones",
                vec!["project_id", "semantic_sha256"],
            ),
            (
                "uq_knowledge_packet_submission",
                "knowledge_evidence_packets",
                vec!["project_id", "run_id"],
            ),
            (
                "uq_knowledge_versioned_proposal_submission",
                "knowledge_versioned_proposals",
                vec!["project_id", "run_id"],
            ),
        ] {
            let mut index = Index::create();
            index.name(name).table(Alias::new(table)).unique();
            for column in columns {
                index.col(Alias::new(column));
            }
            manager
                .create_index(index.if_not_exists().to_owned())
                .await?;
        }
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        for table in [
            "knowledge_bootstrap_scope_cones",
            "knowledge_evidence_packets",
            "knowledge_evidence_packet_claims",
            "knowledge_evidence_packet_omissions",
            "knowledge_evidence_packet_conflicts",
            "knowledge_versioned_proposals",
            "knowledge_versioned_proposal_packets",
            "knowledge_versioned_proposal_claims",
        ] {
            let row = manager
                .get_connection()
                .query_one(
                    manager.get_database_backend().build(
                        &Query::select()
                            .expr_as(Expr::expr(Func::count(Expr::col(Asterisk))), Columns::Count)
                            .from(Alias::new(table))
                            .to_owned(),
                    ),
                )
                .await?;
            let count = row
                .map(|row| row.try_get::<i64>("", "count"))
                .transpose()?
                .unwrap_or_default();
            if count > 0 {
                return Err(DbErr::Custom(format!(
                    "cannot downgrade migration 051 while authoritative rows remain in {table}"
                )));
            }
        }
        // Packets and proposals are authoritative durable evidence. Older binaries ignore the
        // additive tables; rollback never removes or synthesizes their history.
        Ok(())
    }
}

fn knowledge_evidence_proposal_tables() -> Vec<TableCreateStatement> {
    vec![
        Table::create()
            .table(Tables::KnowledgeBootstrapScopeCones)
            .if_not_exists()
            .col(ColumnDef::new(Columns::Id).text().not_null().primary_key())
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::CycleId).text().not_null())
            .col(ColumnDef::new(Columns::ShardId).text().not_null())
            .col(ColumnDef::new(Columns::AcquisitionId).text().not_null())
            .col(ColumnDef::new(Columns::Fence).big_integer().not_null())
            .col(ColumnDef::new(Columns::Attempt).big_integer().not_null())
            .col(ColumnDef::new(Columns::InventoryId).text().not_null())
            .col(ColumnDef::new(Columns::SourceSnapshotId).text().not_null())
            .col(
                ColumnDef::new(Columns::UninitializedKnowledgeSha256)
                    .text()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::SemanticSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::SemanticSha256).text().not_null())
            .col(ColumnDef::new(Columns::ResultSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::ArtifactSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::ArtifactId).text().not_null())
            .col(ColumnDef::new(Columns::ArtifactSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::IncludedCount)
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::AbsenceProofCount)
                    .big_integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .col(ColumnDef::new(Columns::VerifiedAt).text().not_null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeBootstrapScopeCones)
                    .from_col(Columns::ProjectId)
                    .to_tbl(Tables::Projects)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeBootstrapScopeCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .to_tbl(Tables::KnowledgeCycles)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeBootstrapScopeCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::ShardId)
                    .to_tbl(Tables::KnowledgeCycleShards)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeBootstrapScopeCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeLeaseAcquisitions)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeBootstrapScopeCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::InventoryId)
                    .from_col(Columns::ShardId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .from_col(Columns::SourceSnapshotId)
                    .from_col(Columns::UninitializedKnowledgeSha256)
                    .to_tbl(Tables::KnowledgeInventoryManifests)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .to_col(Columns::ShardId)
                    .to_col(Columns::AcquisitionId)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .to_col(Columns::SourceSnapshotId)
                    .to_col(Columns::UninitializedKnowledgeSha256),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeBootstrapScopeCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::SourceSnapshotId)
                    .to_tbl(Tables::KnowledgeSourceSnapshots)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeBootstrapScopeCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::ArtifactId)
                    .from_col(Columns::ArtifactSha256)
                    .to_tbl(Tables::KnowledgeExternalArtifacts)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Sha256),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                )
                .eq(36)
                .and(Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id))))),
            )
            .check(
                Expr::col(Columns::SemanticSchemaVersion)
                    .eq(1)
                    .and(Expr::col(Columns::ArtifactSchemaVersion).eq(1)),
            )
            .check(
                Expr::col(Columns::Fence)
                    .gt(0)
                    .and(Expr::col(Columns::Attempt).gt(0)),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length")).args([SimpleExpr::from(Expr::col(
                        Columns::UninitializedKnowledgeSha256,
                    ))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::UninitializedKnowledgeSha256).eq(Expr::expr(Func::lower(
                        Expr::col(Columns::UninitializedKnowledgeSha256),
                    ))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::SemanticSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::SemanticSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::SemanticSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ResultSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ResultSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ResultSha256)))),
                ),
            )
            .check(Expr::col(Columns::SemanticSha256).eq(Expr::col(Columns::ResultSha256)))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ArtifactSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ArtifactSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ArtifactSha256)))),
                ),
            )
            .check(
                Expr::col(Columns::IncludedCount)
                    .gte(0)
                    .and(Expr::col(Columns::AbsenceProofCount).gte(0)),
            )
            .check(Expr::col(Columns::VerifiedAt).gte(Expr::col(Columns::CreatedAt)))
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::Id),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::SemanticSha256),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeEvidencePackets)
            .if_not_exists()
            .col(ColumnDef::new(Columns::Id).text().not_null().primary_key())
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::CycleId).text().not_null())
            .col(ColumnDef::new(Columns::ShardId).text().not_null())
            .col(ColumnDef::new(Columns::RunId).big_integer().not_null())
            .col(ColumnDef::new(Columns::AcquisitionId).text().not_null())
            .col(ColumnDef::new(Columns::Fence).big_integer().not_null())
            .col(ColumnDef::new(Columns::Attempt).big_integer().not_null())
            .col(ColumnDef::new(Columns::StableShardSha256).text().not_null())
            .col(ColumnDef::new(Columns::ComputationSha256).text().not_null())
            .col(ColumnDef::new(Columns::ToolchainSha256).text().not_null())
            .col(ColumnDef::new(Columns::InputKind).text().not_null())
            .col(ColumnDef::new(Columns::SourceSnapshotId).text().not_null())
            .col(ColumnDef::new(Columns::InventoryId).text().not_null())
            .col(ColumnDef::new(Columns::ScopeId).text().not_null())
            .col(ColumnDef::new(Columns::KnowledgeRevision).text().null())
            .col(ColumnDef::new(Columns::KnowledgeViewSha256).text().null())
            .col(ColumnDef::new(Columns::GraphSha256).text().null())
            .col(
                ColumnDef::new(Columns::UninitializedKnowledgeSha256)
                    .text()
                    .null(),
            )
            .col(ColumnDef::new(Columns::SubmissionSha256).text().not_null())
            .col(ColumnDef::new(Columns::PacketSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::ArtifactSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::ArtifactId).text().not_null())
            .col(ColumnDef::new(Columns::ArtifactSha256).text().not_null())
            .col(ColumnDef::new(Columns::Outcome).text().not_null())
            .col(ColumnDef::new(Columns::ClaimCount).big_integer().not_null())
            .col(
                ColumnDef::new(Columns::OmissionCount)
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::ConflictCount)
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::ReferenceCount)
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::UnresolvedSelectorCount)
                    .big_integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .col(ColumnDef::new(Columns::VerifiedAt).text().not_null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePackets)
                    .from_col(Columns::ProjectId)
                    .to_tbl(Tables::Projects)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePackets)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .to_tbl(Tables::KnowledgeCycles)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePackets)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::ShardId)
                    .to_tbl(Tables::KnowledgeCycleShards)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePackets)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::RunId)
                    .to_tbl(Tables::KnowledgeCycleRunBindings)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::RunId)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePackets)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::RunId)
                    .from_col(Columns::ShardId)
                    .from_col(Columns::StableShardSha256)
                    .from_col(Columns::ComputationSha256)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeCycleRunBindings)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::RunId)
                    .to_col(Columns::ShardId)
                    .to_col(Columns::StableShardSha256)
                    .to_col(Columns::ComputationSha256)
                    .to_col(Columns::AcquisitionId)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePackets)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeLeaseAcquisitions)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePackets)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::SourceSnapshotId)
                    .to_tbl(Tables::KnowledgeSourceSnapshots)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePackets)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::InventoryId)
                    .from_col(Columns::SourceSnapshotId)
                    .to_tbl(Tables::KnowledgeInventoryManifests)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .to_col(Columns::SourceSnapshotId),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePackets)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::ArtifactId)
                    .from_col(Columns::ArtifactSha256)
                    .to_tbl(Tables::KnowledgeExternalArtifacts)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Sha256),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                )
                .eq(36)
                .and(Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id))))),
            )
            .check(
                Expr::col(Columns::Fence)
                    .gt(0)
                    .and(Expr::col(Columns::Attempt).gt(0))
                    .and(Expr::col(Columns::ArtifactSchemaVersion).eq(1)),
            )
            .check(
                Expr::col(Columns::InputKind)
                    .is_in([Expr::val("accepted"), Expr::val("bootstrap")]),
            )
            .check(Expr::col(Columns::Outcome).is_in([
                Expr::val("complete"),
                Expr::val("partial"),
                Expr::val("blocked"),
                Expr::val("failed"),
            ]))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::SubmissionSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::SubmissionSha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::SubmissionSha256,
                    )))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::PacketSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::PacketSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::PacketSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ArtifactSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ArtifactSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ArtifactSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::StableShardSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::StableShardSha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::StableShardSha256,
                    )))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ComputationSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ComputationSha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::ComputationSha256,
                    )))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ToolchainSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ToolchainSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ToolchainSha256)))),
                ),
            )
            .check(
                Expr::col(Columns::ClaimCount)
                    .between(0, 4096)
                    .and(Expr::col(Columns::OmissionCount).between(0, 4096))
                    .and(Expr::col(Columns::ConflictCount).between(0, 2048))
                    .and(Expr::col(Columns::ReferenceCount).between(0, 16384))
                    .and(Expr::col(Columns::UnresolvedSelectorCount).between(0, 16384)),
            )
            .check(
                Expr::col(Columns::InputKind)
                    .eq("accepted")
                    .and(Expr::expr(Expr::col(Columns::KnowledgeRevision).is_null()).not())
                    .and(Expr::expr(Expr::col(Columns::KnowledgeViewSha256).is_null()).not())
                    .and(Expr::expr(Expr::col(Columns::GraphSha256).is_null()).not())
                    .and(Expr::col(Columns::UninitializedKnowledgeSha256).is_null())
                    .or(Expr::col(Columns::InputKind)
                        .eq("bootstrap")
                        .and(Expr::col(Columns::KnowledgeRevision).is_null())
                        .and(Expr::col(Columns::KnowledgeViewSha256).is_null())
                        .and(Expr::col(Columns::GraphSha256).is_null())
                        .and(
                            Expr::expr(Expr::col(Columns::UninitializedKnowledgeSha256).is_null())
                                .not(),
                        )),
            )
            .check(Expr::col(Columns::VerifiedAt).gte(Expr::col(Columns::CreatedAt)))
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::Id),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::Id)
                    .col(Columns::PacketSha256),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::RunId),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeEvidencePacketClaims)
            .if_not_exists()
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::PacketId).text().not_null())
            .col(ColumnDef::new(Columns::Ordinal).big_integer().not_null())
            .col(ColumnDef::new(Columns::ClaimId).text().not_null())
            .col(ColumnDef::new(Columns::ClaimSha256).text().not_null())
            .col(ColumnDef::new(Columns::EpistemicClass).text().not_null())
            .col(ColumnDef::new(Columns::RetentionKind).text().not_null())
            .col(
                ColumnDef::new(Columns::SupportCount)
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::ContradictionCount)
                    .big_integer()
                    .not_null(),
            )
            .primary_key(
                Index::create()
                    .col(Columns::ProjectId)
                    .col(Columns::PacketId)
                    .col(Columns::Ordinal),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePacketClaims)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::PacketId)
                    .to_tbl(Tables::KnowledgeEvidencePackets)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .check(
                Expr::col(Columns::Ordinal)
                    .gte(0)
                    .and(Expr::col(Columns::SupportCount).gte(0))
                    .and(Expr::col(Columns::ContradictionCount).gte(0)),
            )
            .check(Expr::col(Columns::EpistemicClass).is_in([
                Expr::val("observed"),
                Expr::val("inferred"),
                Expr::val("unknown"),
                Expr::val("conflicting"),
            ]))
            .check(
                Expr::col(Columns::RetentionKind)
                    .is_in([Expr::val("mandatory"), Expr::val("scored")]),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ClaimSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ClaimSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ClaimSha256)))),
                ),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::PacketId)
                    .col(Columns::ClaimId),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeEvidencePacketOmissions)
            .if_not_exists()
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::PacketId).text().not_null())
            .col(ColumnDef::new(Columns::Ordinal).big_integer().not_null())
            .col(
                ColumnDef::new(Columns::SourceIdentitySha256)
                    .text()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::Reason).text().not_null())
            .col(ColumnDef::new(Columns::SafeDetailSha256).text().null())
            .primary_key(
                Index::create()
                    .col(Columns::ProjectId)
                    .col(Columns::PacketId)
                    .col(Columns::Ordinal),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePacketOmissions)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::PacketId)
                    .to_tbl(Tables::KnowledgeEvidencePackets)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .check(Expr::col(Columns::Ordinal).gte(0))
            .check(Expr::col(Columns::Reason).is_in([
                Expr::val("sensitive"),
                Expr::val("digest_only"),
                Expr::val("ineligible"),
                Expr::val("unreadable"),
                Expr::val("over_budget"),
                Expr::val("outside_shard"),
                Expr::val("unknown"),
            ]))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::SourceIdentitySha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::SourceIdentitySha256).eq(Expr::expr(Func::lower(
                        Expr::col(Columns::SourceIdentitySha256),
                    ))),
                ),
            )
            .check(
                Expr::col(Columns::SafeDetailSha256)
                    .is_null()
                    .or(Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::SafeDetailSha256))]),
                    )
                    .eq(64)
                    .and(
                        Expr::col(Columns::SafeDetailSha256).eq(Expr::expr(Func::lower(
                            Expr::col(Columns::SafeDetailSha256),
                        ))),
                    )),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::PacketId)
                    .col(Columns::SourceIdentitySha256),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeEvidencePacketConflicts)
            .if_not_exists()
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::PacketId).text().not_null())
            .col(ColumnDef::new(Columns::Ordinal).big_integer().not_null())
            .col(ColumnDef::new(Columns::ConflictId).text().not_null())
            .col(ColumnDef::new(Columns::ConflictSha256).text().not_null())
            .col(ColumnDef::new(Columns::Kind).text().not_null())
            .primary_key(
                Index::create()
                    .col(Columns::ProjectId)
                    .col(Columns::PacketId)
                    .col(Columns::Ordinal),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeEvidencePacketConflicts)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::PacketId)
                    .to_tbl(Tables::KnowledgeEvidencePackets)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .check(Expr::col(Columns::Ordinal).gte(0))
            .check(Expr::col(Columns::Kind).is_in([
                Expr::val("source_disagreement"),
                Expr::val("canonical_disagreement"),
                Expr::val("ownership_ambiguity"),
                Expr::val("unsupported_normative_claim"),
            ]))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ConflictSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ConflictSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ConflictSha256)))),
                ),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::PacketId)
                    .col(Columns::ConflictId),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeVersionedProposals)
            .if_not_exists()
            .col(ColumnDef::new(Columns::Id).text().not_null().primary_key())
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::CycleId).text().not_null())
            .col(ColumnDef::new(Columns::RunId).big_integer().not_null())
            .col(ColumnDef::new(Columns::AcquisitionId).text().not_null())
            .col(ColumnDef::new(Columns::Fence).big_integer().not_null())
            .col(ColumnDef::new(Columns::Attempt).big_integer().not_null())
            .col(ColumnDef::new(Columns::ComputationSha256).text().not_null())
            .col(ColumnDef::new(Columns::ToolchainSha256).text().not_null())
            .col(ColumnDef::new(Columns::InputKind).text().not_null())
            .col(ColumnDef::new(Columns::SourceSnapshotId).text().not_null())
            .col(ColumnDef::new(Columns::InventoryId).text().not_null())
            .col(ColumnDef::new(Columns::ScopeId).text().not_null())
            .col(ColumnDef::new(Columns::KnowledgeRevision).text().null())
            .col(ColumnDef::new(Columns::KnowledgeViewSha256).text().null())
            .col(ColumnDef::new(Columns::GraphSha256).text().null())
            .col(
                ColumnDef::new(Columns::UninitializedKnowledgeSha256)
                    .text()
                    .null(),
            )
            .col(ColumnDef::new(Columns::CandidateKind).text().not_null())
            .col(ColumnDef::new(Columns::SubmissionSha256).text().not_null())
            .col(ColumnDef::new(Columns::ProposalSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::ArtifactSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::ArtifactId).text().not_null())
            .col(ColumnDef::new(Columns::ArtifactSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::PacketCount)
                    .big_integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::ClaimCount).big_integer().not_null())
            .col(
                ColumnDef::new(Columns::OmissionCount)
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::ConflictCount)
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::UnresolvedSelectorCount)
                    .big_integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .col(ColumnDef::new(Columns::VerifiedAt).text().not_null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposals)
                    .from_col(Columns::ProjectId)
                    .to_tbl(Tables::Projects)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposals)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .to_tbl(Tables::KnowledgeCycles)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposals)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::RunId)
                    .to_tbl(Tables::KnowledgeCycleRunBindings)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::RunId)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposals)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::RunId)
                    .from_col(Columns::ComputationSha256)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeCycleRunBindings)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::RunId)
                    .to_col(Columns::ComputationSha256)
                    .to_col(Columns::AcquisitionId)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposals)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeLeaseAcquisitions)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposals)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::SourceSnapshotId)
                    .to_tbl(Tables::KnowledgeSourceSnapshots)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposals)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::InventoryId)
                    .from_col(Columns::SourceSnapshotId)
                    .to_tbl(Tables::KnowledgeInventoryManifests)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .to_col(Columns::SourceSnapshotId),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposals)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::ArtifactId)
                    .from_col(Columns::ArtifactSha256)
                    .to_tbl(Tables::KnowledgeExternalArtifacts)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Sha256),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                )
                .eq(36)
                .and(Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id))))),
            )
            .check(
                Expr::col(Columns::Fence)
                    .gt(0)
                    .and(Expr::col(Columns::Attempt).gt(0))
                    .and(Expr::col(Columns::ArtifactSchemaVersion).eq(1)),
            )
            .check(
                Expr::col(Columns::InputKind)
                    .is_in([Expr::val("accepted"), Expr::val("bootstrap")]),
            )
            .check(
                Expr::col(Columns::CandidateKind)
                    .is_in([Expr::val("initialize"), Expr::val("change")]),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::SubmissionSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::SubmissionSha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::SubmissionSha256,
                    )))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ProposalSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ProposalSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ProposalSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ArtifactSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ArtifactSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ArtifactSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ComputationSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ComputationSha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::ComputationSha256,
                    )))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ToolchainSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ToolchainSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ToolchainSha256)))),
                ),
            )
            .check(
                Expr::col(Columns::PacketCount)
                    .between(1, 1024)
                    .and(Expr::col(Columns::ClaimCount).between(0, 4096))
                    .and(Expr::col(Columns::OmissionCount).between(0, 4096))
                    .and(Expr::col(Columns::ConflictCount).between(0, 2048))
                    .and(Expr::col(Columns::UnresolvedSelectorCount).between(0, 16384)),
            )
            .check(
                Expr::col(Columns::InputKind)
                    .eq("accepted")
                    .and(Expr::col(Columns::CandidateKind).eq("change"))
                    .and(Expr::expr(Expr::col(Columns::KnowledgeRevision).is_null()).not())
                    .and(Expr::expr(Expr::col(Columns::KnowledgeViewSha256).is_null()).not())
                    .and(Expr::expr(Expr::col(Columns::GraphSha256).is_null()).not())
                    .and(Expr::col(Columns::UninitializedKnowledgeSha256).is_null())
                    .or(Expr::col(Columns::InputKind)
                        .eq("bootstrap")
                        .and(Expr::col(Columns::CandidateKind).eq("initialize"))
                        .and(Expr::col(Columns::KnowledgeRevision).is_null())
                        .and(Expr::col(Columns::KnowledgeViewSha256).is_null())
                        .and(Expr::col(Columns::GraphSha256).is_null())
                        .and(
                            Expr::expr(Expr::col(Columns::UninitializedKnowledgeSha256).is_null())
                                .not(),
                        )),
            )
            .check(Expr::col(Columns::VerifiedAt).gte(Expr::col(Columns::CreatedAt)))
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::Id),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::RunId),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeVersionedProposalPackets)
            .if_not_exists()
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::ProposalId).text().not_null())
            .col(ColumnDef::new(Columns::Ordinal).big_integer().not_null())
            .col(ColumnDef::new(Columns::PacketId).text().not_null())
            .col(ColumnDef::new(Columns::PacketSha256).text().not_null())
            .primary_key(
                Index::create()
                    .col(Columns::ProjectId)
                    .col(Columns::ProposalId)
                    .col(Columns::Ordinal),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposalPackets)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::ProposalId)
                    .to_tbl(Tables::KnowledgeVersionedProposals)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposalPackets)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::PacketId)
                    .from_col(Columns::PacketSha256)
                    .to_tbl(Tables::KnowledgeEvidencePackets)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::PacketSha256),
            )
            .check(Expr::col(Columns::Ordinal).gte(0))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::PacketSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::PacketSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::PacketSha256)))),
                ),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::ProposalId)
                    .col(Columns::PacketId),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeVersionedProposalClaims)
            .if_not_exists()
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::ProposalId).text().not_null())
            .col(ColumnDef::new(Columns::Ordinal).big_integer().not_null())
            .col(ColumnDef::new(Columns::ClaimId).text().not_null())
            .col(ColumnDef::new(Columns::ClaimSha256).text().not_null())
            .col(ColumnDef::new(Columns::Disposition).text().not_null())
            .col(ColumnDef::new(Columns::OwnerNodeId).text().null())
            .primary_key(
                Index::create()
                    .col(Columns::ProjectId)
                    .col(Columns::ProposalId)
                    .col(Columns::Ordinal),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeVersionedProposalClaims)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::ProposalId)
                    .to_tbl(Tables::KnowledgeVersionedProposals)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .check(Expr::col(Columns::Ordinal).gte(0))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ClaimSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ClaimSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ClaimSha256)))),
                ),
            )
            .check(Expr::col(Columns::Disposition).is_in([
                Expr::val("retain"),
                Expr::val("refresh"),
                Expr::val("promote"),
                Expr::val("demote"),
                Expr::val("move"),
                Expr::val("split"),
                Expr::val("merge"),
                Expr::val("supersede"),
                Expr::val("remove"),
                Expr::val("unresolved"),
            ]))
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::ProposalId)
                    .col(Columns::ClaimId),
            )
            .to_owned(),
    ]
}

#[derive(DeriveIden)]
enum Tables {
    KnowledgeBootstrapScopeCones,
    KnowledgeCycleRunBindings,
    KnowledgeCycleShards,
    KnowledgeCycles,
    KnowledgeEvidencePacketClaims,
    KnowledgeEvidencePacketConflicts,
    KnowledgeEvidencePacketOmissions,
    KnowledgeEvidencePackets,
    KnowledgeExternalArtifacts,
    KnowledgeInventoryManifests,
    KnowledgeLeaseAcquisitions,
    KnowledgeSourceSnapshots,
    KnowledgeVersionedProposalClaims,
    KnowledgeVersionedProposalPackets,
    KnowledgeVersionedProposals,
    Projects,
}

#[derive(DeriveIden)]
enum Columns {
    AbsenceProofCount,
    AcquisitionId,
    ArtifactId,
    ArtifactSchemaVersion,
    ArtifactSha256,
    Attempt,
    CandidateKind,
    ClaimCount,
    ClaimId,
    ClaimSha256,
    ComputationSha256,
    ConflictCount,
    ConflictId,
    ConflictSha256,
    ContradictionCount,
    Count,
    CreatedAt,
    CycleId,
    Disposition,
    EpistemicClass,
    Fence,
    GraphSha256,
    Id,
    IncludedCount,
    InputKind,
    InventoryId,
    Kind,
    KnowledgeRevision,
    KnowledgeViewSha256,
    OmissionCount,
    Ordinal,
    Outcome,
    OwnerNodeId,
    PacketCount,
    PacketId,
    PacketSha256,
    ProjectId,
    ProposalId,
    ProposalSha256,
    Reason,
    ReferenceCount,
    ResultSha256,
    RetentionKind,
    RunId,
    SafeDetailSha256,
    ScopeId,
    SemanticSchemaVersion,
    SemanticSha256,
    Sha256,
    ShardId,
    SourceIdentitySha256,
    SourceSnapshotId,
    StableShardSha256,
    SubmissionSha256,
    SupportCount,
    ToolchainSha256,
    UninitializedKnowledgeSha256,
    UnresolvedSelectorCount,
    VerifiedAt,
}

#[cfg(test)]
mod tests {
    use super::*;
    use assertr::prelude::*;

    fn normalize(sql: &str) -> String {
        sql.chars()
            .filter(|c| !c.is_whitespace() && *c != '"')
            .flat_map(char::to_uppercase)
            .collect()
    }

    #[test]
    fn evidence_proposal_tables_are_ordered_externalized_and_postgres_portable() {
        let sql = knowledge_evidence_proposal_tables()
            .iter()
            .map(|table| normalize(&table.to_string(PostgresQueryBuilder)))
            .collect::<Vec<_>>();
        assert_that!(&sql.len()).is_equal_to(8);
        for (index, table) in [
            "knowledge_bootstrap_scope_cones",
            "knowledge_evidence_packets",
            "knowledge_evidence_packet_claims",
            "knowledge_evidence_packet_omissions",
            "knowledge_evidence_packet_conflicts",
            "knowledge_versioned_proposals",
            "knowledge_versioned_proposal_packets",
            "knowledge_versioned_proposal_claims",
        ]
        .into_iter()
        .enumerate()
        {
            assert_that!(&sql[index])
                .contains(normalize(&format!("CREATE TABLE IF NOT EXISTS {table}")));
            assert_that!(&sql[index]).does_not_contain(normalize("AUTOINCREMENT"));
            assert_that!(&sql[index]).does_not_contain(normalize("packet_json"));
            assert_that!(&sql[index]).does_not_contain(normalize("proposal_json"));
        }
        assert_that!(&sql[0]).contains(normalize("REFERENCES knowledge_inventory_manifests(project_id, cycle_id, id, shard_id, acquisition_id, fence, attempt, source_snapshot_id, uninitialized_knowledge_sha256)"));
        assert_that!(&sql[1]).contains(normalize(
            "REFERENCES knowledge_cycle_run_bindings(project_id, run_id)",
        ));
        assert_that!(&sql[1]).contains(normalize("REFERENCES knowledge_cycle_run_bindings(project_id, cycle_id, run_id, shard_id, stable_shard_sha256, computation_sha256, acquisition_id, fence, attempt)"));
        assert_that!(&sql[1]).contains(normalize("REFERENCES knowledge_inventory_manifests(project_id, cycle_id, id, source_snapshot_id)"));
        assert_that!(&sql[1]).contains(normalize("reference_count BETWEEN 0 AND 16384"));
        assert_that!(&sql[1]).contains(normalize("toolchain_sha256 TEXT NOT NULL"));
        assert_that!(&sql[5]).contains(normalize("candidate_kind IN ('initialize','change')"));
        assert_that!(&sql[5]).contains(normalize("packet_count BETWEEN 1 AND 1024"));
        assert_that!(&sql[5]).contains(normalize("REFERENCES knowledge_cycle_run_bindings(project_id, cycle_id, run_id, computation_sha256, acquisition_id, fence, attempt)"));
        assert_that!(&sql[6]).contains(normalize(
            "REFERENCES knowledge_evidence_packets(project_id, id, packet_sha256)",
        ));
    }
}
