use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_query::{Func, SimpleExpr};

use super::super::AgentRuns;
use super::super::Projects;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260904_000045_add_knowledge_operational_foundations"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        create_knowledge_operational_foundation_tables(manager).await
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        // These tables contain durable audit history. Binary rollback intentionally leaves both
        // schema and rows in place; reapplying this idempotent migration is therefore safe.
        Ok(())
    }
}

async fn create_knowledge_operational_foundation_tables(
    manager: &SchemaManager<'_>,
) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(KnowledgeTables::ExternalArtifacts)
                .if_not_exists()
                .col(ColumnDef::new(Columns::Id).string_len(36).not_null())
                .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
                .col(ColumnDef::new(Columns::StorageBackend).string().not_null())
                .col(ColumnDef::new(Columns::StorageKey).string().not_null())
                .col(ColumnDef::new(Columns::MediaType).string().not_null())
                .col(ColumnDef::new(Columns::Sha256).string_len(64).not_null())
                .col(ColumnDef::new(Columns::ByteLength).big_integer().not_null())
                .col(ColumnDef::new(Columns::CreatedAt).string().not_null())
                .col(ColumnDef::new(Columns::VerifiedAt).string().not_null())
                .primary_key(Index::create().col(Columns::Id))
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_knowledge_external_artifacts_project")
                        .from(KnowledgeTables::ExternalArtifacts, Columns::ProjectId)
                        .to(Projects::Table, Projects::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .check(Expr::col(Columns::StorageBackend).eq("local_file_v1"))
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                    )
                    .eq(36)
                    .and(
                        Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id)))),
                    ),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::Sha256))]),
                    )
                    .eq(64)
                    .and(
                        Expr::col(Columns::Sha256)
                            .eq(Expr::expr(Func::lower(Expr::col(Columns::Sha256)))),
                    ),
                )
                .check(Expr::col(Columns::ByteLength).gte(0))
                .to_owned(),
        )
        .await?;
    for index in [
        Index::create()
            .name("uq_knowledge_external_artifacts_project_id")
            .table(KnowledgeTables::ExternalArtifacts)
            .col(Columns::ProjectId)
            .col(Columns::Id)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_knowledge_external_artifacts_storage_key")
            .table(KnowledgeTables::ExternalArtifacts)
            .col(Columns::StorageBackend)
            .col(Columns::StorageKey)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_knowledge_external_artifacts_project_sha")
            .table(KnowledgeTables::ExternalArtifacts)
            .col(Columns::ProjectId)
            .col(Columns::Sha256)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_knowledge_external_artifacts_project_created")
            .table(KnowledgeTables::ExternalArtifacts)
            .col(Columns::ProjectId)
            .col(Columns::CreatedAt)
            .if_not_exists()
            .to_owned(),
    ] {
        manager.create_index(index).await?;
    }

    manager
        .create_table(
            Table::create()
                .table(Columns::KnowledgeIgnoreSnapshots)
                .if_not_exists()
                .col(ColumnDef::new(Columns::Id).string_len(36).not_null())
                .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
                .col(ColumnDef::new(Columns::StoreUuid).string_len(36).not_null())
                .col(ColumnDef::new(Columns::SchemaVersion).integer().not_null())
                .col(
                    ColumnDef::new(Columns::MatcherSchemaVersion)
                        .integer()
                        .not_null(),
                )
                .col(ColumnDef::new(Columns::MatcherVersion).string().not_null())
                .col(
                    ColumnDef::new(Columns::KnowledgeIgnoreSha256)
                        .string_len(64)
                        .not_null(),
                )
                .col(ColumnDef::new(Columns::State).string().not_null())
                .col(
                    ColumnDef::new(Columns::ControlCount)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Columns::ParseFailureCount)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(Columns::CreatedAt).string().not_null())
                .primary_key(Index::create().col(Columns::Id))
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_knowledge_ignore_snapshots_project")
                        .from(Columns::KnowledgeIgnoreSnapshots, Columns::ProjectId)
                        .to(Projects::Table, Projects::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                    )
                    .eq(36)
                    .and(
                        Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id)))),
                    ),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::StoreUuid))]),
                    )
                    .eq(36)
                    .and(
                        Expr::col(Columns::StoreUuid)
                            .eq(Expr::expr(Func::lower(Expr::col(Columns::StoreUuid)))),
                    ),
                )
                .check(
                    Expr::col(Columns::SchemaVersion)
                        .gt(0)
                        .and(Expr::col(Columns::MatcherSchemaVersion).gt(0)),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::MatcherVersion))]),
                    )
                    .gt(0),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::KnowledgeIgnoreSha256))]),
                    )
                    .eq(64)
                    .and(
                        Expr::col(Columns::KnowledgeIgnoreSha256).eq(Expr::expr(Func::lower(
                            Expr::col(Columns::KnowledgeIgnoreSha256),
                        ))),
                    ),
                )
                .check(Expr::col(Columns::State).is_in([Expr::val("valid"), Expr::val("invalid")]))
                .check(
                    Expr::col(Columns::ControlCount)
                        .gte(0)
                        .and(Expr::col(Columns::ParseFailureCount).gte(0)),
                )
                .to_owned(),
        )
        .await?;
    for index in [
        Index::create()
            .name("uq_knowledge_ignore_snapshots_project_id")
            .table(Columns::KnowledgeIgnoreSnapshots)
            .col(Columns::ProjectId)
            .col(Columns::Id)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_knowledge_ignore_snapshots_identity")
            .table(Columns::KnowledgeIgnoreSnapshots)
            .col(Columns::ProjectId)
            .col(Columns::StoreUuid)
            .col(Columns::KnowledgeIgnoreSha256)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_knowledge_ignore_snapshots_project_created")
            .table(Columns::KnowledgeIgnoreSnapshots)
            .col(Columns::ProjectId)
            .col(Columns::CreatedAt)
            .if_not_exists()
            .to_owned(),
    ] {
        manager.create_index(index).await?;
    }

    manager
        .create_table(
            Table::create()
                .table(KnowledgeTables::SourceSnapshots)
                .if_not_exists()
                .col(ColumnDef::new(Columns::Id).string_len(36).not_null())
                .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
                .col(ColumnDef::new(Columns::StoreUuid).string_len(36).not_null())
                .col(ColumnDef::new(Columns::SchemaVersion).integer().not_null())
                .col(ColumnDef::new(Columns::SourceKind).string().not_null())
                .col(
                    ColumnDef::new(Columns::SnapshotSha256)
                        .string_len(64)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Columns::SourceScopeSha256)
                        .string_len(64)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Columns::KnowledgeIgnoreSha256)
                        .string_len(64)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Columns::ManifestSha256)
                        .string_len(64)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Columns::IgnoreSnapshotId)
                        .string_len(36)
                        .not_null(),
                )
                .col(ColumnDef::new(Columns::CreatedAt).string().not_null())
                .primary_key(Index::create().col(Columns::Id))
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_knowledge_source_snapshots_project")
                        .from(KnowledgeTables::SourceSnapshots, Columns::ProjectId)
                        .to(Projects::Table, Projects::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_knowledge_source_snapshots_ignore")
                        .from(
                            KnowledgeTables::SourceSnapshots,
                            (Columns::ProjectId, Columns::IgnoreSnapshotId),
                        )
                        .to(
                            Columns::KnowledgeIgnoreSnapshots,
                            (Columns::ProjectId, Columns::Id),
                        ),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                    )
                    .eq(36)
                    .and(
                        Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id)))),
                    ),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::StoreUuid))]),
                    )
                    .eq(36)
                    .and(
                        Expr::col(Columns::StoreUuid)
                            .eq(Expr::expr(Func::lower(Expr::col(Columns::StoreUuid)))),
                    ),
                )
                .check(Expr::col(Columns::SchemaVersion).gt(0))
                .check(
                    Expr::col(Columns::SourceKind)
                        .is_in([Expr::val("git"), Expr::val("filesystem")]),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::SnapshotSha256))]),
                    )
                    .eq(64)
                    .and(
                        Expr::expr(
                            Func::cust(Alias::new("length"))
                                .args([SimpleExpr::from(Expr::col(Columns::SourceScopeSha256))]),
                        )
                        .eq(64),
                    )
                    .and(
                        Expr::expr(
                            Func::cust(Alias::new("length")).args([SimpleExpr::from(Expr::col(
                                Columns::KnowledgeIgnoreSha256,
                            ))]),
                        )
                        .eq(64),
                    )
                    .and(
                        Expr::expr(
                            Func::cust(Alias::new("length"))
                                .args([SimpleExpr::from(Expr::col(Columns::ManifestSha256))]),
                        )
                        .eq(64),
                    ),
                )
                .check(
                    Expr::col(Columns::SnapshotSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::SnapshotSha256))))
                        .and(
                            Expr::col(Columns::SourceScopeSha256).eq(Expr::expr(Func::lower(
                                Expr::col(Columns::SourceScopeSha256),
                            ))),
                        )
                        .and(
                            Expr::col(Columns::KnowledgeIgnoreSha256).eq(Expr::expr(Func::lower(
                                Expr::col(Columns::KnowledgeIgnoreSha256),
                            ))),
                        )
                        .and(
                            Expr::col(Columns::ManifestSha256)
                                .eq(Expr::expr(Func::lower(Expr::col(Columns::ManifestSha256)))),
                        ),
                )
                .to_owned(),
        )
        .await?;
    for index in [
        Index::create()
            .name("uq_knowledge_source_snapshots_project_id")
            .table(KnowledgeTables::SourceSnapshots)
            .col(Columns::ProjectId)
            .col(Columns::Id)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_knowledge_source_snapshots_project_sha")
            .table(KnowledgeTables::SourceSnapshots)
            .col(Columns::ProjectId)
            .col(Columns::SnapshotSha256)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_knowledge_source_snapshots_project_created")
            .table(KnowledgeTables::SourceSnapshots)
            .col(Columns::ProjectId)
            .col(Columns::CreatedAt)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_knowledge_source_snapshots_ignore")
            .table(KnowledgeTables::SourceSnapshots)
            .col(Columns::ProjectId)
            .col(Columns::IgnoreSnapshotId)
            .if_not_exists()
            .to_owned(),
    ] {
        manager.create_index(index).await?;
    }

    manager
        .create_table(
            Table::create()
                .table(KnowledgeTables::Cycles)
                .if_not_exists()
                .col(ColumnDef::new(Columns::Id).string_len(36).not_null())
                .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
                .col(ColumnDef::new(Columns::StoreUuid).string_len(36).not_null())
                .col(ColumnDef::new(Columns::Kind).string().not_null())
                .col(ColumnDef::new(Columns::Status).string().not_null())
                .col(ColumnDef::new(Columns::Phase).string().null())
                .col(ColumnDef::new(Columns::WaitingReason).string().null())
                .col(ColumnDef::new(Columns::TerminalOutcome).string().null())
                .col(
                    ColumnDef::new(Columns::Version)
                        .big_integer()
                        .not_null()
                        .default(1),
                )
                .col(
                    ColumnDef::new(Columns::KnowledgeRevision)
                        .string_len(64)
                        .null(),
                )
                .col(
                    ColumnDef::new(Columns::SourceSnapshotId)
                        .string_len(36)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Columns::IgnoreSnapshotId)
                        .string_len(36)
                        .not_null(),
                )
                .col(ColumnDef::new(Columns::RequestKey).string().null())
                .col(
                    ColumnDef::new(Columns::AnalysisSha256)
                        .string_len(64)
                        .null(),
                )
                .col(ColumnDef::new(Columns::ScopeSchemaVersion).integer().null())
                .col(ColumnDef::new(Columns::ScopeJson).text().null())
                .col(ColumnDef::new(Columns::ScopeSha256).string_len(64).null())
                .col(
                    ColumnDef::new(Columns::CancellationActorKind)
                        .string()
                        .null(),
                )
                .col(ColumnDef::new(Columns::CancellationActorId).string().null())
                .col(ColumnDef::new(Columns::CancellationReason).text().null())
                .col(ColumnDef::new(Columns::CancelledAt).string().null())
                .col(ColumnDef::new(Columns::ErrorCode).string().null())
                .col(ColumnDef::new(Columns::ErrorMessage).text().null())
                .col(ColumnDef::new(Columns::StartedAt).string().null())
                .col(ColumnDef::new(Columns::FinishedAt).string().null())
                .col(ColumnDef::new(Columns::CreatedAt).string().not_null())
                .col(ColumnDef::new(Columns::UpdatedAt).string().not_null())
                .primary_key(Index::create().col(Columns::Id))
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_knowledge_cycles_project")
                        .from(KnowledgeTables::Cycles, Columns::ProjectId)
                        .to(Projects::Table, Projects::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_knowledge_cycles_source_snapshot")
                        .from(
                            KnowledgeTables::Cycles,
                            (Columns::ProjectId, Columns::SourceSnapshotId),
                        )
                        .to(
                            KnowledgeTables::SourceSnapshots,
                            (Columns::ProjectId, Columns::Id),
                        ),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_knowledge_cycles_ignore_snapshot")
                        .from(
                            KnowledgeTables::Cycles,
                            (Columns::ProjectId, Columns::IgnoreSnapshotId),
                        )
                        .to(
                            Columns::KnowledgeIgnoreSnapshots,
                            (Columns::ProjectId, Columns::Id),
                        ),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                    )
                    .eq(36)
                    .and(
                        Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id)))),
                    ),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::StoreUuid))]),
                    )
                    .eq(36)
                    .and(
                        Expr::col(Columns::StoreUuid)
                            .eq(Expr::expr(Func::lower(Expr::col(Columns::StoreUuid)))),
                    ),
                )
                .check(Expr::col(Columns::Kind).is_in([
                    Expr::val("bootstrap"),
                    Expr::val("incremental"),
                    Expr::val("comprehensive"),
                    Expr::val("repair"),
                    Expr::val("toolchain_revalidation"),
                ]))
                .check(Expr::col(Columns::Status).is_in([
                    Expr::val("queued"),
                    Expr::val("running"),
                    Expr::val("waiting"),
                    Expr::val("completed"),
                    Expr::val("failed"),
                    Expr::val("cancelled"),
                ]))
                .check(
                    Expr::col(Columns::Phase)
                        .is_null()
                        .or(Expr::col(Columns::Phase).is_in([
                            Expr::val("preflight"),
                            Expr::val("snapshot"),
                            Expr::val("inventory"),
                            Expr::val("scope"),
                            Expr::val("extract"),
                            Expr::val("reduce"),
                            Expr::val("validate"),
                            Expr::val("decide"),
                            Expr::val("apply"),
                            Expr::val("finalize"),
                            Expr::val("verify"),
                        ])),
                )
                .check(Expr::col(Columns::WaitingReason).is_null().or(
                    Expr::col(Columns::WaitingReason).is_in([
                        Expr::val("human_decision"),
                        Expr::val("more_evidence"),
                        Expr::val("retry_backoff"),
                        Expr::val("manual_unblock"),
                    ]),
                ))
                .check(Expr::col(Columns::TerminalOutcome).is_null().or(
                    Expr::col(Columns::TerminalOutcome).is_in([
                        Expr::val("no_change"),
                        Expr::val("applied"),
                        Expr::val("rejected"),
                        Expr::val("blocked"),
                        Expr::val("superseded"),
                        Expr::val("failed"),
                        Expr::val("cancelled"),
                    ]),
                ))
                .check(Expr::col(Columns::Version).gt(0))
                .check(
                    Expr::col(Columns::ScopeSchemaVersion)
                        .is_null()
                        .and(Expr::col(Columns::ScopeJson).is_null())
                        .and(Expr::col(Columns::ScopeSha256).is_null())
                        .or(Expr::col(Columns::ScopeSchemaVersion)
                            .gt(0)
                            .and(Expr::col(Columns::ScopeJson).is_null().not())
                            .and(Expr::col(Columns::ScopeSha256).is_null().not())),
                )
                .check(
                    Expr::col(Columns::CancellationActorKind)
                        .is_null()
                        .and(Expr::col(Columns::CancellationActorId).is_null())
                        .and(Expr::col(Columns::CancellationReason).is_null())
                        .and(Expr::col(Columns::CancelledAt).is_null())
                        .or(Expr::col(Columns::CancellationActorKind)
                            .is_in([
                                Expr::val("service"),
                                Expr::val("human"),
                                Expr::val("agent_run"),
                            ])
                            .and(Expr::col(Columns::CancellationReason).is_null().not())
                            .and(Expr::col(Columns::CancelledAt).is_null().not())
                            .and(
                                Expr::col(Columns::CancellationActorKind)
                                    .eq("service")
                                    .and(Expr::col(Columns::CancellationActorId).is_null())
                                    .or(Expr::col(Columns::CancellationActorKind)
                                        .ne("service")
                                        .and(
                                            Expr::col(Columns::CancellationActorId).is_null().not(),
                                        )
                                        .and(
                                            Expr::expr(Func::cust(Alias::new("length")).args([
                                                SimpleExpr::from(Expr::col(
                                                    Columns::CancellationActorId,
                                                )),
                                            ]))
                                            .gt(0),
                                        )),
                            )),
                )
                .to_owned(),
        )
        .await?;
    for index in [
        Index::create()
            .name("uq_knowledge_cycles_project_id")
            .table(KnowledgeTables::Cycles)
            .col(Columns::ProjectId)
            .col(Columns::Id)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_knowledge_cycles_project_request")
            .table(KnowledgeTables::Cycles)
            .col(Columns::ProjectId)
            .col(Columns::RequestKey)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_knowledge_cycles_project_status_time")
            .table(KnowledgeTables::Cycles)
            .col(Columns::ProjectId)
            .col(Columns::Status)
            .col(Columns::CreatedAt)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_knowledge_cycles_project_kind_status")
            .table(KnowledgeTables::Cycles)
            .col(Columns::ProjectId)
            .col(Columns::Kind)
            .col(Columns::Status)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_knowledge_cycles_store_status")
            .table(KnowledgeTables::Cycles)
            .col(Columns::StoreUuid)
            .col(Columns::Status)
            .if_not_exists()
            .to_owned(),
    ] {
        manager.create_index(index).await?;
    }

    manager
        .create_index(
            Index::create()
                .name("uq_agent_runs_project_id")
                .table(AgentRuns::Table)
                .col(AgentRuns::ProjectId)
                .col(AgentRuns::Id)
                .unique()
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(KnowledgeTables::CycleEvents)
                .if_not_exists()
                .col(ColumnDef::new(Columns::Id).string_len(36).not_null())
                .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
                .col(ColumnDef::new(Columns::CycleId).string_len(36).not_null())
                .col(ColumnDef::new(Columns::Sequence).big_integer().not_null())
                .col(ColumnDef::new(Columns::Kind).string().not_null())
                .col(
                    ColumnDef::new(Columns::PriorVersion)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(Columns::ResultingVersion)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(Columns::ActorKind).string().not_null())
                .col(ColumnDef::new(Columns::ActorId).string().null())
                .col(ColumnDef::new(Columns::InputSha256).string_len(64).null())
                .col(ColumnDef::new(Columns::OutputSha256).string_len(64).null())
                .col(ColumnDef::new(Columns::CreatedAt).string().not_null())
                .primary_key(Index::create().col(Columns::Id))
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_knowledge_cycle_events_cycle")
                        .from(
                            KnowledgeTables::CycleEvents,
                            (Columns::ProjectId, Columns::CycleId),
                        )
                        .to(KnowledgeTables::Cycles, (Columns::ProjectId, Columns::Id))
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                    )
                    .eq(36)
                    .and(
                        Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id)))),
                    ),
                )
                .check(
                    Expr::col(Columns::Sequence)
                        .gt(0)
                        .and(Expr::col(Columns::PriorVersion).gte(0))
                        .and(Expr::col(Columns::ResultingVersion).gt(0)),
                )
                .check(
                    Expr::col(Columns::ResultingVersion)
                        .eq(Expr::col(Columns::PriorVersion).add(Expr::val(1))),
                )
                .check(Expr::col(Columns::Kind).is_in([
                    Expr::val("created"),
                    Expr::val("transitioned"),
                    Expr::val("snapshot_linked"),
                    Expr::val("run_linked"),
                    Expr::val("artifact_linked"),
                ]))
                .check(Expr::col(Columns::ActorKind).is_in([
                    Expr::val("service"),
                    Expr::val("human"),
                    Expr::val("agent_run"),
                ]))
                .check(
                    Expr::col(Columns::ActorKind)
                        .eq("service")
                        .and(Expr::col(Columns::ActorId).is_null())
                        .or(Expr::col(Columns::ActorKind)
                            .ne("service")
                            .and(Expr::col(Columns::ActorId).is_null().not())
                            .and(
                                Expr::expr(
                                    Func::cust(Alias::new("length"))
                                        .args([SimpleExpr::from(Expr::col(Columns::ActorId))]),
                                )
                                .gt(0),
                            )),
                )
                .to_owned(),
        )
        .await?;
    for index in [
        Index::create()
            .name("uq_knowledge_cycle_events_sequence")
            .table(KnowledgeTables::CycleEvents)
            .col(Columns::CycleId)
            .col(Columns::Sequence)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_knowledge_cycle_events_resulting_version")
            .table(KnowledgeTables::CycleEvents)
            .col(Columns::CycleId)
            .col(Columns::ResultingVersion)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_knowledge_cycle_events_project_id")
            .table(KnowledgeTables::CycleEvents)
            .col(Columns::ProjectId)
            .col(Columns::Id)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_knowledge_cycle_events_project_created")
            .table(KnowledgeTables::CycleEvents)
            .col(Columns::ProjectId)
            .col(Columns::CreatedAt)
            .if_not_exists()
            .to_owned(),
    ] {
        manager.create_index(index).await?;
    }

    manager
        .create_table(
            Table::create()
                .table(KnowledgeTables::CycleRuns)
                .if_not_exists()
                .col(ColumnDef::new(Columns::Id).string_len(36).not_null())
                .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
                .col(ColumnDef::new(Columns::CycleId).string_len(36).not_null())
                .col(ColumnDef::new(Columns::AgentRunId).big_integer().not_null())
                .col(ColumnDef::new(Columns::Role).string().not_null())
                .col(ColumnDef::new(Columns::Attempt).big_integer().not_null())
                .col(ColumnDef::new(Columns::LinkedAt).string().not_null())
                .primary_key(Index::create().col(Columns::Id))
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_knowledge_cycle_runs_cycle")
                        .from(
                            KnowledgeTables::CycleRuns,
                            (Columns::ProjectId, Columns::CycleId),
                        )
                        .to(KnowledgeTables::Cycles, (Columns::ProjectId, Columns::Id))
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_knowledge_cycle_runs_agent_run")
                        .from(
                            KnowledgeTables::CycleRuns,
                            (Columns::ProjectId, Columns::AgentRunId),
                        )
                        .to(AgentRuns::Table, (AgentRuns::ProjectId, AgentRuns::Id))
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .check(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                    )
                    .eq(36)
                    .and(
                        Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id)))),
                    ),
                )
                .check(Expr::col(Columns::Role).is_in([
                    Expr::val("coordinator"),
                    Expr::val("scout"),
                    Expr::val("reducer"),
                    Expr::val("verifier"),
                ]))
                .check(Expr::col(Columns::Attempt).gt(0))
                .to_owned(),
        )
        .await?;
    for index in [
        Index::create()
            .name("uq_knowledge_cycle_runs_agent_run")
            .table(KnowledgeTables::CycleRuns)
            .col(Columns::AgentRunId)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_knowledge_cycle_runs_cycle_run_role")
            .table(KnowledgeTables::CycleRuns)
            .col(Columns::CycleId)
            .col(Columns::AgentRunId)
            .col(Columns::Role)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_knowledge_cycle_runs_role_attempt_time")
            .table(KnowledgeTables::CycleRuns)
            .col(Columns::Role)
            .col(Columns::Attempt)
            .col(Columns::LinkedAt)
            .if_not_exists()
            .to_owned(),
    ] {
        manager.create_index(index).await?;
    }

    for (table, owner_table, owner_column, purpose) in [
        (
            "knowledge_cycle_artifacts",
            "knowledge_cycles",
            "cycle_id",
            None,
        ),
        (
            "knowledge_cycle_event_artifacts",
            "knowledge_cycle_events",
            "cycle_event_id",
            None,
        ),
        (
            "knowledge_source_snapshot_artifacts",
            "knowledge_source_snapshots",
            "source_snapshot_id",
            Some("manifest"),
        ),
        (
            "knowledge_ignore_snapshot_artifacts",
            "knowledge_ignore_snapshots",
            "ignore_snapshot_id",
            Some("matcher_input"),
        ),
    ] {
        let mut statement = Table::create();
        statement
            .table(Alias::new(table))
            .if_not_exists()
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(
                ColumnDef::new(Alias::new(owner_column))
                    .string_len(36)
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::ArtifactId)
                    .string_len(36)
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::Purpose).string().not_null())
            .col(ColumnDef::new(Columns::CreatedAt).string().not_null())
            .primary_key(
                Index::create()
                    .col(Columns::ProjectId)
                    .col(Alias::new(owner_column))
                    .col(Columns::ArtifactId)
                    .col(Columns::Purpose),
            )
            .foreign_key(
                ForeignKey::create()
                    .name(format!("fk_{table}_owner"))
                    .from(
                        Alias::new(table),
                        (Columns::ProjectId, Alias::new(owner_column)),
                    )
                    .to(Alias::new(owner_table), (Columns::ProjectId, Columns::Id))
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .name(format!("fk_{table}_artifact"))
                    .from(Alias::new(table), (Columns::ProjectId, Columns::ArtifactId))
                    .to(
                        KnowledgeTables::ExternalArtifacts,
                        (Columns::ProjectId, Columns::Id),
                    ),
            );
        if let Some(purpose) = purpose {
            statement.check(Expr::col(Columns::Purpose).eq(purpose));
            statement.index(
                Index::create()
                    .name(format!("uq_{table}_owner"))
                    .col(Columns::ProjectId)
                    .col(Alias::new(owner_column))
                    .unique(),
            );
        }
        manager.create_table(statement.to_owned()).await?;
        manager
            .create_index(
                Index::create()
                    .name(format!("idx_{table}_artifact"))
                    .table(Alias::new(table))
                    .col(Columns::ArtifactId)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;
    }

    Ok(())
}

#[derive(DeriveIden)]
enum Columns {
    ActorId,
    ActorKind,
    AgentRunId,
    AnalysisSha256,
    ArtifactId,
    Attempt,
    ByteLength,
    CancellationActorId,
    CancellationActorKind,
    CancellationReason,
    CancelledAt,
    ControlCount,
    CreatedAt,
    CycleId,
    ErrorCode,
    ErrorMessage,
    FinishedAt,
    Id,
    IgnoreSnapshotId,
    InputSha256,
    Kind,
    KnowledgeIgnoreSha256,
    KnowledgeIgnoreSnapshots,
    KnowledgeRevision,
    LinkedAt,
    ManifestSha256,
    MatcherSchemaVersion,
    MatcherVersion,
    MediaType,
    OutputSha256,
    ParseFailureCount,
    Phase,
    PriorVersion,
    ProjectId,
    Purpose,
    RequestKey,
    ResultingVersion,
    Role,
    SchemaVersion,
    ScopeJson,
    ScopeSchemaVersion,
    ScopeSha256,
    Sequence,
    Sha256,
    SnapshotSha256,
    SourceKind,
    SourceScopeSha256,
    SourceSnapshotId,
    StartedAt,
    State,
    Status,
    StorageBackend,
    StorageKey,
    StoreUuid,
    TerminalOutcome,
    UpdatedAt,
    VerifiedAt,
    Version,
    WaitingReason,
}

#[derive(Iden)]
enum KnowledgeTables {
    #[iden = "knowledge_cycle_events"]
    CycleEvents,
    #[iden = "knowledge_cycle_runs"]
    CycleRuns,
    #[iden = "knowledge_cycles"]
    Cycles,
    #[iden = "knowledge_external_artifacts"]
    ExternalArtifacts,
    #[iden = "knowledge_source_snapshots"]
    SourceSnapshots,
}
