use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_query::{Asterisk, Func, SimpleExpr, TableCreateStatement};

use super::super::create_read_view;
use super::add_column_if_missing;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260905_000049_support_knowledge_agent_runs"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        support_knowledge_agent_runs(manager).await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        for table in [
            "agent_run_launch_contracts",
            "agent_run_skill_provenance",
            "knowledge_cycle_run_bindings",
            "knowledge_cycle_run_outcomes",
        ] {
            let row = manager
                .get_connection()
                .query_one(
                    manager.get_database_backend().build(
                        &Query::select()
                            .expr_as(Expr::expr(Func::count(Expr::col(Asterisk))), Columns::Count)
                            .from(Alias::new(table))
                            .to_owned(),
                    ),
                )
                .await?;
            let count = row
                .map(|row| row.try_get::<i64>("", "count"))
                .transpose()?
                .unwrap_or_default();
            if count > 0 {
                return Err(DbErr::Custom(format!(
                    "cannot downgrade migration 049 while authoritative rows remain in {table}"
                )));
            }
        }
        for table in [
            "knowledge_cycle_run_outcomes",
            "knowledge_cycle_run_bindings",
            "agent_run_skill_provenance",
            "agent_run_launch_contracts",
        ] {
            manager
                .drop_table(
                    Table::drop()
                        .table(Alias::new(table))
                        .if_exists()
                        .to_owned(),
                )
                .await?;
        }
        // The nullable compatibility projection is harmless to older binaries and intentionally
        // remains so a failed downgrade cannot discard its meaning.
        Ok(())
    }
}

fn knowledge_agent_run_tables() -> Vec<TableCreateStatement> {
    vec![
        Table::create()
            .table(Tables::AgentRunLaunchContracts)
            .if_not_exists()
            .col(
                ColumnDef::new(Columns::RunId)
                    .big_integer()
                    .not_null()
                    .primary_key(),
            )
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::Purpose).text().not_null())
            .col(ColumnDef::new(Columns::State).text().not_null())
            .col(
                ColumnDef::new(Columns::TargetSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::TargetJson).text().not_null())
            .col(ColumnDef::new(Columns::TargetSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::ResolutionSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::ResolutionJson).text().not_null())
            .col(ColumnDef::new(Columns::ResolutionSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::CapabilitySchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::CapabilityJson).text().not_null())
            .col(ColumnDef::new(Columns::CapabilitySha256).text().not_null())
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .col(ColumnDef::new(Columns::UpdatedAt).text().not_null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::AgentRunLaunchContracts)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::RunId)
                    .to_tbl(Tables::AgentRuns)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .check(Expr::col(Columns::Purpose).is_in([
                Expr::val("ordinary"),
                Expr::val("knowledge_answer"),
                Expr::val("knowledge_cycle"),
            ]))
            .check(Expr::col(Columns::State).is_in([
                Expr::val("allocated"),
                Expr::val("prepared"),
                Expr::val("target_resolved"),
                Expr::val("spawned"),
                Expr::val("terminal"),
            ]))
            .check(
                Expr::col(Columns::TargetSchemaVersion)
                    .eq(1)
                    .and(Expr::col(Columns::ResolutionSchemaVersion).eq(1))
                    .and(Expr::col(Columns::CapabilitySchemaVersion).eq(1)),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::TargetJson))]),
                )
                .between(2, 16384)
                .and(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::ResolutionJson))]),
                    )
                    .between(2, 16384),
                )
                .and(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::CapabilityJson))]),
                    )
                    .between(2, 16384),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::TargetSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::TargetSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::TargetSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ResolutionSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ResolutionSha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::ResolutionSha256,
                    )))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::CapabilitySha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::CapabilitySha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::CapabilitySha256,
                    )))),
                ),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::RunId),
            )
            .to_owned(),
        Table::create()
            .table(Tables::AgentRunSkillProvenance)
            .if_not_exists()
            .col(ColumnDef::new(Columns::Id).text().not_null().primary_key())
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::RunId).big_integer().not_null())
            .col(ColumnDef::new(Columns::Ordinal).integer().not_null())
            .col(ColumnDef::new(Columns::SchemaVersion).integer().not_null())
            .col(ColumnDef::new(Columns::ProvenanceJson).text().not_null())
            .col(ColumnDef::new(Columns::ProvenanceSha256).text().not_null())
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::AgentRunSkillProvenance)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::RunId)
                    .to_tbl(Tables::AgentRunLaunchContracts)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::RunId)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                )
                .eq(36)
                .and(Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id))))),
            )
            .check(
                Expr::col(Columns::Ordinal)
                    .gte(0)
                    .and(Expr::col(Columns::SchemaVersion).eq(1)),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ProvenanceJson))]),
                )
                .between(2, 16384),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ProvenanceSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ProvenanceSha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::ProvenanceSha256,
                    )))),
                ),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::RunId)
                    .col(Columns::Ordinal),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::RunId)
                    .col(Columns::ProvenanceSha256),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeCycleRunBindings)
            .if_not_exists()
            .col(
                ColumnDef::new(Columns::RunId)
                    .big_integer()
                    .not_null()
                    .primary_key(),
            )
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(
                ColumnDef::new(Columns::CycleRunId)
                    .text()
                    .not_null()
                    .unique_key(),
            )
            .col(ColumnDef::new(Columns::CycleId).text().not_null())
            .col(ColumnDef::new(Columns::StoreUuid).text().not_null())
            .col(ColumnDef::new(Columns::SlotId).text().not_null())
            .col(ColumnDef::new(Columns::ShardId).text().null())
            .col(ColumnDef::new(Columns::StableShardSha256).text().null())
            .col(ColumnDef::new(Columns::ComputationSha256).text().not_null())
            .col(ColumnDef::new(Columns::AcquisitionId).text().not_null())
            .col(ColumnDef::new(Columns::Fence).big_integer().not_null())
            .col(ColumnDef::new(Columns::Attempt).big_integer().not_null())
            .col(
                ColumnDef::new(Columns::RoleSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::RoleJson).text().not_null())
            .col(ColumnDef::new(Columns::RoleSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::LaunchSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::LaunchJson).text().not_null())
            .col(ColumnDef::new(Columns::LaunchSha256).text().not_null())
            .col(ColumnDef::new(Columns::CapabilitySha256).text().not_null())
            .col(ColumnDef::new(Columns::SkillsSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::PinnedConfigSha256)
                    .text()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::PromptSha256).text().not_null())
            .col(ColumnDef::new(Columns::CredentialSha256).text().not_null())
            .col(ColumnDef::new(Columns::ProviderThreadId).text().null())
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeCycleRunBindings)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::RunId)
                    .to_tbl(Tables::AgentRunLaunchContracts)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::RunId)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeCycleRunBindings)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::CycleRunId)
                    .to_tbl(Tables::KnowledgeCycleRuns)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeCycleRunBindings)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .to_tbl(Tables::KnowledgeCycles)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeCycleRunBindings)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::SlotId)
                    .to_tbl(Tables::KnowledgeLeaseSlots)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeCycleRunBindings)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::ShardId)
                    .to_tbl(Tables::KnowledgeCycleShards)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeCycleRunBindings)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeLeaseAcquisitions)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .check(
                Expr::col(Columns::Fence)
                    .gt(0)
                    .and(Expr::col(Columns::Attempt).gt(0))
                    .and(Expr::col(Columns::RoleSchemaVersion).eq(1))
                    .and(Expr::col(Columns::LaunchSchemaVersion).eq(1)),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::CycleRunId))]),
                )
                .eq(36)
                .and(
                    Expr::col(Columns::CycleRunId)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::CycleRunId)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::CycleId))]),
                )
                .eq(36)
                .and(
                    Expr::col(Columns::CycleId)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::CycleId)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::StoreUuid))]),
                )
                .eq(36)
                .and(
                    Expr::col(Columns::StoreUuid)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::StoreUuid)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::SlotId))]),
                )
                .eq(36)
                .and(
                    Expr::col(Columns::SlotId)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::SlotId)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::AcquisitionId))]),
                )
                .eq(36)
                .and(
                    Expr::col(Columns::AcquisitionId)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::AcquisitionId)))),
                ),
            )
            .check(
                Expr::col(Columns::ShardId)
                    .is_null()
                    .and(Expr::col(Columns::StableShardSha256).is_null())
                    .or(Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::ShardId))]),
                    )
                    .eq(36)
                    .and(
                        Expr::col(Columns::ShardId)
                            .eq(Expr::expr(Func::lower(Expr::col(Columns::ShardId)))),
                    )
                    .and(
                        Expr::expr(
                            Func::cust(Alias::new("length"))
                                .args([SimpleExpr::from(Expr::col(Columns::StableShardSha256))]),
                        )
                        .eq(64),
                    )
                    .and(
                        Expr::col(Columns::StableShardSha256).eq(Expr::expr(Func::lower(
                            Expr::col(Columns::StableShardSha256),
                        ))),
                    )),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::RoleJson))]),
                )
                .between(2, 16384)
                .and(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::LaunchJson))]),
                    )
                    .between(2, 16384),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::RoleSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::RoleSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::RoleSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::LaunchSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::LaunchSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::LaunchSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ComputationSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ComputationSha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::ComputationSha256,
                    )))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::CapabilitySha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::CapabilitySha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::CapabilitySha256,
                    )))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::SkillsSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::SkillsSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::SkillsSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::PinnedConfigSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::PinnedConfigSha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::PinnedConfigSha256,
                    )))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::PromptSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::PromptSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::PromptSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::CredentialSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::CredentialSha256).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::CredentialSha256,
                    )))),
                ),
            )
            .check(
                Expr::col(Columns::ProviderThreadId)
                    .is_null()
                    .or(Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::ProviderThreadId))]),
                    )
                    .between(1, 512)),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::RunId),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::CycleRunId),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::AcquisitionId)
                    .col(Columns::LaunchSha256),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeCycleRunOutcomes)
            .if_not_exists()
            .col(
                ColumnDef::new(Columns::RunId)
                    .big_integer()
                    .not_null()
                    .primary_key(),
            )
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::CycleRunId).text().not_null())
            .col(ColumnDef::new(Columns::CycleId).text().not_null())
            .col(ColumnDef::new(Columns::AcquisitionId).text().not_null())
            .col(ColumnDef::new(Columns::Fence).big_integer().not_null())
            .col(ColumnDef::new(Columns::Attempt).big_integer().not_null())
            .col(ColumnDef::new(Columns::Role).text().not_null())
            .col(ColumnDef::new(Columns::SchemaVersion).integer().not_null())
            .col(ColumnDef::new(Columns::OutcomeJson).text().not_null())
            .col(ColumnDef::new(Columns::OutcomeSha256).text().not_null())
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeCycleRunOutcomes)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::RunId)
                    .to_tbl(Tables::KnowledgeCycleRunBindings)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::RunId)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeCycleRunOutcomes)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::CycleRunId)
                    .to_tbl(Tables::KnowledgeCycleRuns)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeCycleRunOutcomes)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeLeaseAcquisitions)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .check(
                Expr::col(Columns::SchemaVersion).eq(1).and(
                    Expr::expr(
                        Func::cust(Alias::new("length"))
                            .args([SimpleExpr::from(Expr::col(Columns::OutcomeJson))]),
                    )
                    .between(2, 16384),
                ),
            )
            .check(
                Expr::col(Columns::Fence)
                    .gt(0)
                    .and(Expr::col(Columns::Attempt).gt(0)),
            )
            .check(Expr::col(Columns::Role).is_in([
                Expr::val("coordinator"),
                Expr::val("scout"),
                Expr::val("reducer"),
                Expr::val("verifier"),
            ]))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::OutcomeSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::OutcomeSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::OutcomeSha256)))),
                ),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::RunId),
            )
            .to_owned(),
    ]
}

async fn support_knowledge_agent_runs(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    add_column_if_missing(
        manager,
        "agent_runs",
        ColumnDef::new(Columns::Purpose)
            .text()
            .check(
                Expr::col(Columns::Purpose)
                    .is_null()
                    .or(Expr::col(Columns::Purpose).is_in([
                        Expr::val("ordinary"),
                        Expr::val("knowledge_answer"),
                        Expr::val("knowledge_cycle"),
                    ])),
            )
            .to_owned(),
    )
    .await?;
    create_read_view(manager, "agent_runs", "agent_runs_read_view").await?;
    manager
        .create_index(
            Index::create()
                .name("uq_knowledge_cycle_runs_project_id")
                .table(Tables::KnowledgeCycleRuns)
                .col(Columns::ProjectId)
                .col(Columns::Id)
                .unique()
                .if_not_exists()
                .to_owned(),
        )
        .await?;
    for index in [
        Index::create()
            .name("uq_knowledge_cycle_runs_project_cycle_id")
            .table(Tables::KnowledgeCycleRuns)
            .col(Columns::ProjectId)
            .col(Columns::CycleId)
            .col(Columns::Id)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_cycle_shards_project_cycle_id")
            .table(Tables::KnowledgeCycleShards)
            .col(Columns::ProjectId)
            .col(Columns::CycleId)
            .col(Columns::Id)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_lease_acquisitions_project_guard")
            .table(Tables::KnowledgeLeaseAcquisitions)
            .col(Columns::ProjectId)
            .col(Columns::Id)
            .col(Columns::Fence)
            .col(Columns::Attempt)
            .unique()
            .if_not_exists()
            .to_owned(),
    ] {
        manager.create_index(index).await?;
    }
    for table in knowledge_agent_run_tables() {
        manager.create_table(table).await?;
    }
    for index in [
        Index::create()
            .name("idx_agent_run_launch_state")
            .table(Tables::AgentRunLaunchContracts)
            .col(Columns::ProjectId)
            .col(Columns::State)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_cycle_run_launch_acquisition")
            .table(Tables::KnowledgeCycleRunBindings)
            .col(Columns::ProjectId)
            .col(Columns::AcquisitionId)
            .unique()
            .if_not_exists()
            .to_owned(),
    ] {
        manager.create_index(index).await?;
    }
    Ok(())
}

#[derive(DeriveIden)]
enum Tables {
    AgentRunLaunchContracts,
    AgentRunSkillProvenance,
    AgentRuns,
    KnowledgeCycleRunBindings,
    KnowledgeCycleRunOutcomes,
    KnowledgeCycleRuns,
    KnowledgeCycleShards,
    KnowledgeCycles,
    KnowledgeLeaseAcquisitions,
    KnowledgeLeaseSlots,
}

#[derive(DeriveIden)]
enum Columns {
    AcquisitionId,
    Attempt,
    CapabilityJson,
    CapabilitySchemaVersion,
    CapabilitySha256,
    ComputationSha256,
    Count,
    CreatedAt,
    CredentialSha256,
    CycleId,
    CycleRunId,
    Fence,
    Id,
    LaunchJson,
    LaunchSchemaVersion,
    LaunchSha256,
    Ordinal,
    OutcomeJson,
    OutcomeSha256,
    PinnedConfigSha256,
    ProjectId,
    PromptSha256,
    ProvenanceJson,
    ProvenanceSha256,
    ProviderThreadId,
    Purpose,
    ResolutionJson,
    ResolutionSchemaVersion,
    ResolutionSha256,
    Role,
    RoleJson,
    RoleSchemaVersion,
    RoleSha256,
    RunId,
    SchemaVersion,
    ShardId,
    SkillsSha256,
    SlotId,
    StableShardSha256,
    State,
    StoreUuid,
    TargetJson,
    TargetSchemaVersion,
    TargetSha256,
    UpdatedAt,
}

#[cfg(test)]
mod tests {
    use super::*;
    use assertr::prelude::*;

    fn normalize(sql: &str) -> String {
        sql.chars()
            .filter(|c| !c.is_whitespace() && *c != '"')
            .flat_map(char::to_uppercase)
            .collect()
    }

    #[test]
    fn knowledge_agent_run_tables_are_ordered_and_postgres_portable() {
        let sql = knowledge_agent_run_tables()
            .iter()
            .map(|table| normalize(&table.to_string(PostgresQueryBuilder)))
            .collect::<Vec<_>>();
        assert_that!(&sql.len()).is_equal_to(4);
        for (index, table) in [
            "agent_run_launch_contracts",
            "agent_run_skill_provenance",
            "knowledge_cycle_run_bindings",
            "knowledge_cycle_run_outcomes",
        ]
        .into_iter()
        .enumerate()
        {
            assert_that!(&sql[index])
                .contains(normalize(&format!("CREATE TABLE IF NOT EXISTS {table}")));
            assert_that!(&sql[index]).does_not_contain(normalize("AUTOINCREMENT"));
        }
        assert_that!(&sql[0]).contains(normalize("UNIQUE (project_id, run_id)"));
        assert_that!(&sql[1]).contains(normalize(
            "REFERENCES agent_run_launch_contracts(project_id, run_id)",
        ));
        assert_that!(&sql[2]).contains(normalize(
            "REFERENCES knowledge_cycle_runs(project_id, cycle_id, id)",
        ));
        assert_that!(&sql[2]).contains(normalize(
            "REFERENCES knowledge_lease_acquisitions(project_id, id, fence, attempt)",
        ));
        assert_that!(&sql[3]).contains(normalize(
            "REFERENCES knowledge_cycle_run_bindings(project_id, run_id)",
        ));
    }
}
