[package]
name = "dispatch-operator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dispatch-operator"
path = "src/main.rs"

[dependencies]
clap = { version = "4", default-features = false, features = ["color", "derive", "env", "error-context", "help", "std", "suggestions", "usage"] }
dispatch-api-client = { path = "../dispatch-api-client", default-features = false }
dispatch-types = { path = "../dispatch-types", default-features = false }
rootcause = { version = "0.13.0", default-features = false }
serde = { version = "1", default-features = false, features = ["std"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }
yaml_serde = { version = "0.10", default-features = false }

[dev-dependencies]
assertr = { version = "0.6.0", default-features = false, features = ["std"] }
