use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_query::{Func, SimpleExpr, TableCreateStatement};

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260905_000050_add_knowledge_inventory_impact"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Composite parent identities must exist before the portable same-project child FKs.
        for (name, table, columns) in [
            (
                "uq_external_artifact_inventory_binding",
                "knowledge_external_artifacts",
                vec!["project_id", "id", "sha256"],
            ),
            (
                "uq_computation_output_inventory_binding",
                "knowledge_computation_outputs",
                vec![
                    "project_id",
                    "id",
                    "cycle_id",
                    "shard_id",
                    "acquisition_id",
                    "fence",
                    "output_sha256",
                ],
            ),
        ] {
            let mut index = Index::create();
            index.name(name).table(Alias::new(table)).unique();
            for column in columns {
                index.col(Alias::new(column));
            }
            manager
                .create_index(index.if_not_exists().to_owned())
                .await?;
        }
        for table in knowledge_inventory_impact_tables() {
            manager.create_table(table).await?;
        }
        for (name, table, columns, unique) in [
            (
                "uq_knowledge_inventory_semantic",
                "knowledge_inventory_manifests",
                vec!["project_id", "semantic_sha256"],
                true,
            ),
            (
                "uq_knowledge_impact_cone_semantic",
                "knowledge_impact_cones",
                vec!["project_id", "semantic_sha256"],
                true,
            ),
            (
                "idx_knowledge_inventory_attempt_state",
                "knowledge_inventory_attempts",
                vec!["project_id", "state", "created_at"],
                false,
            ),
            (
                "idx_knowledge_impact_attempt_state",
                "knowledge_impact_cone_attempts",
                vec!["project_id", "state", "created_at"],
                false,
            ),
        ] {
            let mut index = Index::create();
            index.name(name).table(Alias::new(table));
            for column in columns {
                index.col(Alias::new(column));
            }
            if unique {
                index.unique();
            }
            manager
                .create_index(index.if_not_exists().to_owned())
                .await?;
        }
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        // Inventory and impact results are durable evidence. Older binaries ignore these
        // additive tables; rollback deliberately preserves every row and artifact reference.
        Ok(())
    }
}

fn knowledge_inventory_impact_tables() -> Vec<TableCreateStatement> {
    vec![
        Table::create()
            .table(Tables::KnowledgeInventoryManifests)
            .if_not_exists()
            .col(ColumnDef::new(Columns::Id).text().not_null().primary_key())
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::CycleId).text().not_null())
            .col(ColumnDef::new(Columns::ShardId).text().not_null())
            .col(ColumnDef::new(Columns::AcquisitionId).text().not_null())
            .col(ColumnDef::new(Columns::Fence).big_integer().not_null())
            .col(ColumnDef::new(Columns::Attempt).big_integer().not_null())
            .col(ColumnDef::new(Columns::StoreUuid).text().not_null())
            .col(ColumnDef::new(Columns::SourceSnapshotId).text().not_null())
            .col(ColumnDef::new(Columns::KnowledgeRevision).text().null())
            .col(ColumnDef::new(Columns::KnowledgeViewSha256).text().null())
            .col(
                ColumnDef::new(Columns::UninitializedKnowledgeSha256)
                    .text()
                    .null(),
            )
            .col(ColumnDef::new(Columns::GraphSha256).text().null())
            .col(
                ColumnDef::new(Columns::SemanticSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::SemanticSha256).text().not_null())
            .col(ColumnDef::new(Columns::InputSha256).text().not_null())
            .col(ColumnDef::new(Columns::ResultSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::ArtifactSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::ArtifactId).text().not_null())
            .col(ColumnDef::new(Columns::ArtifactSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::ComputationOutputId)
                    .text()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::AccountedCount)
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::EligibleCount)
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::UnownedCount)
                    .big_integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .col(ColumnDef::new(Columns::VerifiedAt).text().not_null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryManifests)
                    .from_col(Columns::ProjectId)
                    .to_tbl(Tables::Projects)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryManifests)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .to_tbl(Tables::KnowledgeCycles)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryManifests)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::ShardId)
                    .to_tbl(Tables::KnowledgeCycleShards)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryManifests)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeLeaseAcquisitions)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryManifests)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::SourceSnapshotId)
                    .to_tbl(Tables::KnowledgeSourceSnapshots)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryManifests)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::ArtifactId)
                    .from_col(Columns::ArtifactSha256)
                    .to_tbl(Tables::KnowledgeExternalArtifacts)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Sha256),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryManifests)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::ComputationOutputId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::ShardId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::ArtifactSha256)
                    .to_tbl(Tables::KnowledgeComputationOutputs)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::ShardId)
                    .to_col(Columns::AcquisitionId)
                    .to_col(Columns::Fence)
                    .to_col(Columns::OutputSha256),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                )
                .eq(36)
                .and(Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id))))),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::StoreUuid))]),
                )
                .eq(36)
                .and(
                    Expr::col(Columns::StoreUuid)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::StoreUuid)))),
                ),
            )
            .check(
                Expr::col(Columns::SemanticSchemaVersion)
                    .eq(1)
                    .and(Expr::col(Columns::ArtifactSchemaVersion).eq(1)),
            )
            .check(
                Expr::col(Columns::Fence)
                    .gt(0)
                    .and(Expr::col(Columns::Attempt).gt(0)),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::SemanticSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::SemanticSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::SemanticSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::InputSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::InputSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::InputSha256)))),
                ),
            )
            .check(Expr::col(Columns::SemanticSha256).eq(Expr::col(Columns::InputSha256)))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ResultSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ResultSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ResultSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ArtifactSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ArtifactSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ArtifactSha256)))),
                ),
            )
            .check(
                Expr::col(Columns::AccountedCount)
                    .gte(0)
                    .and(Expr::col(Columns::EligibleCount).gte(0))
                    .and(Expr::col(Columns::UnownedCount).gte(0)),
            )
            .check(
                Expr::expr(Expr::col(Columns::KnowledgeRevision).is_null())
                    .not()
                    .and(Expr::expr(Expr::col(Columns::KnowledgeViewSha256).is_null()).not())
                    .and(Expr::col(Columns::UninitializedKnowledgeSha256).is_null())
                    .and(Expr::expr(Expr::col(Columns::GraphSha256).is_null()).not())
                    .or(Expr::col(Columns::KnowledgeRevision)
                        .is_null()
                        .and(Expr::col(Columns::KnowledgeViewSha256).is_null())
                        .and(
                            Expr::expr(Expr::col(Columns::UninitializedKnowledgeSha256).is_null())
                                .not(),
                        )
                        .and(Expr::col(Columns::GraphSha256).is_null())),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::Id),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::SemanticSha256),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeImpactCones)
            .if_not_exists()
            .col(ColumnDef::new(Columns::Id).text().not_null().primary_key())
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::CycleId).text().not_null())
            .col(ColumnDef::new(Columns::ShardId).text().not_null())
            .col(ColumnDef::new(Columns::AcquisitionId).text().not_null())
            .col(ColumnDef::new(Columns::Fence).big_integer().not_null())
            .col(ColumnDef::new(Columns::Attempt).big_integer().not_null())
            .col(ColumnDef::new(Columns::InventoryId).text().not_null())
            .col(ColumnDef::new(Columns::KnowledgeRevision).text().not_null())
            .col(ColumnDef::new(Columns::GraphSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::SemanticSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::SemanticSha256).text().not_null())
            .col(ColumnDef::new(Columns::InputSha256).text().not_null())
            .col(ColumnDef::new(Columns::ResultSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::ArtifactSchemaVersion)
                    .integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::ArtifactId).text().not_null())
            .col(ColumnDef::new(Columns::ArtifactSha256).text().not_null())
            .col(
                ColumnDef::new(Columns::ComputationOutputId)
                    .text()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::IncludedCount)
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Columns::ContradictionCount)
                    .big_integer()
                    .not_null(),
            )
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .col(ColumnDef::new(Columns::VerifiedAt).text().not_null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeImpactCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::InventoryId)
                    .to_tbl(Tables::KnowledgeInventoryManifests)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeImpactCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .to_tbl(Tables::KnowledgeCycles)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeImpactCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::ShardId)
                    .to_tbl(Tables::KnowledgeCycleShards)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeImpactCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeLeaseAcquisitions)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeImpactCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::ArtifactId)
                    .from_col(Columns::ArtifactSha256)
                    .to_tbl(Tables::KnowledgeExternalArtifacts)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Sha256),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeImpactCones)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::ComputationOutputId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::ShardId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::ArtifactSha256)
                    .to_tbl(Tables::KnowledgeComputationOutputs)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::ShardId)
                    .to_col(Columns::AcquisitionId)
                    .to_col(Columns::Fence)
                    .to_col(Columns::OutputSha256),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                )
                .eq(36)
                .and(Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id))))),
            )
            .check(
                Expr::col(Columns::SemanticSchemaVersion)
                    .eq(1)
                    .and(Expr::col(Columns::ArtifactSchemaVersion).eq(1)),
            )
            .check(
                Expr::col(Columns::Fence)
                    .gt(0)
                    .and(Expr::col(Columns::Attempt).gt(0)),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::KnowledgeRevision))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::KnowledgeRevision).eq(Expr::expr(Func::lower(Expr::col(
                        Columns::KnowledgeRevision,
                    )))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::GraphSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::GraphSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::GraphSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::SemanticSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::SemanticSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::SemanticSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::InputSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::InputSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::InputSha256)))),
                ),
            )
            .check(Expr::col(Columns::SemanticSha256).eq(Expr::col(Columns::InputSha256)))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ResultSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ResultSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ResultSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ArtifactSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ArtifactSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ArtifactSha256)))),
                ),
            )
            .check(
                Expr::col(Columns::IncludedCount)
                    .gte(0)
                    .and(Expr::col(Columns::ContradictionCount).gte(0)),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::Id),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::SemanticSha256),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeInventoryAttempts)
            .if_not_exists()
            .col(ColumnDef::new(Columns::Id).text().not_null().primary_key())
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::CycleId).text().not_null())
            .col(ColumnDef::new(Columns::ShardId).text().not_null())
            .col(ColumnDef::new(Columns::AcquisitionId).text().not_null())
            .col(ColumnDef::new(Columns::Fence).big_integer().not_null())
            .col(ColumnDef::new(Columns::Attempt).big_integer().not_null())
            .col(ColumnDef::new(Columns::SemanticSha256).text().not_null())
            .col(ColumnDef::new(Columns::InputSha256).text().not_null())
            .col(ColumnDef::new(Columns::State).text().not_null())
            .col(ColumnDef::new(Columns::InventoryId).text().null())
            .col(ColumnDef::new(Columns::ErrorSchemaVersion).integer().null())
            .col(ColumnDef::new(Columns::ErrorJson).text().null())
            .col(ColumnDef::new(Columns::ErrorSha256).text().null())
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .col(ColumnDef::new(Columns::FinishedAt).text().null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryAttempts)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .to_tbl(Tables::KnowledgeCycles)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryAttempts)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::ShardId)
                    .to_tbl(Tables::KnowledgeCycleShards)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryAttempts)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeLeaseAcquisitions)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeInventoryAttempts)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::InventoryId)
                    .to_tbl(Tables::KnowledgeInventoryManifests)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                )
                .eq(36)
                .and(Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id))))),
            )
            .check(
                Expr::col(Columns::Fence)
                    .gt(0)
                    .and(Expr::col(Columns::Attempt).gt(0)),
            )
            .check(Expr::col(Columns::State).is_in([
                Expr::val("pending"),
                Expr::val("completed"),
                Expr::val("reused"),
                Expr::val("failed"),
                Expr::val("cancelled"),
            ]))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::SemanticSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::SemanticSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::SemanticSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::InputSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::InputSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::InputSha256)))),
                ),
            )
            .check(Expr::col(Columns::SemanticSha256).eq(Expr::col(Columns::InputSha256)))
            .check(
                Expr::col(Columns::ErrorSha256).is_null().or(Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ErrorSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ErrorSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ErrorSha256)))),
                )),
            )
            .check(
                Expr::col(Columns::State)
                    .eq("pending")
                    .and(Expr::col(Columns::InventoryId).is_null())
                    .and(Expr::col(Columns::ErrorJson).is_null())
                    .and(Expr::col(Columns::FinishedAt).is_null())
                    .or(Expr::col(Columns::State)
                        .is_in([Expr::val("completed"), Expr::val("reused")])
                        .and(Expr::expr(Expr::col(Columns::InventoryId).is_null()).not())
                        .and(Expr::col(Columns::ErrorJson).is_null())
                        .and(Expr::expr(Expr::col(Columns::FinishedAt).is_null()).not()))
                    .or(Expr::col(Columns::State)
                        .is_in([Expr::val("failed"), Expr::val("cancelled")])
                        .and(Expr::col(Columns::InventoryId).is_null())
                        .and(Expr::col(Columns::ErrorSchemaVersion).eq(1))
                        .and(Expr::expr(Expr::col(Columns::ErrorJson).is_null()).not())
                        .and(Expr::expr(Expr::col(Columns::ErrorSha256).is_null()).not())
                        .and(Expr::expr(Expr::col(Columns::FinishedAt).is_null()).not())),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::Id),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::AcquisitionId)
                    .col(Columns::SemanticSha256),
            )
            .to_owned(),
        Table::create()
            .table(Tables::KnowledgeImpactConeAttempts)
            .if_not_exists()
            .col(ColumnDef::new(Columns::Id).text().not_null().primary_key())
            .col(ColumnDef::new(Columns::ProjectId).big_integer().not_null())
            .col(ColumnDef::new(Columns::CycleId).text().not_null())
            .col(ColumnDef::new(Columns::ShardId).text().not_null())
            .col(ColumnDef::new(Columns::AcquisitionId).text().not_null())
            .col(ColumnDef::new(Columns::Fence).big_integer().not_null())
            .col(ColumnDef::new(Columns::Attempt).big_integer().not_null())
            .col(ColumnDef::new(Columns::SemanticSha256).text().not_null())
            .col(ColumnDef::new(Columns::InputSha256).text().not_null())
            .col(ColumnDef::new(Columns::State).text().not_null())
            .col(ColumnDef::new(Columns::ImpactConeId).text().null())
            .col(ColumnDef::new(Columns::ErrorSchemaVersion).integer().null())
            .col(ColumnDef::new(Columns::ErrorJson).text().null())
            .col(ColumnDef::new(Columns::ErrorSha256).text().null())
            .col(ColumnDef::new(Columns::CreatedAt).text().not_null())
            .col(ColumnDef::new(Columns::FinishedAt).text().null())
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeImpactConeAttempts)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .to_tbl(Tables::KnowledgeCycles)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeImpactConeAttempts)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::CycleId)
                    .from_col(Columns::ShardId)
                    .to_tbl(Tables::KnowledgeCycleShards)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::CycleId)
                    .to_col(Columns::Id)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeImpactConeAttempts)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::AcquisitionId)
                    .from_col(Columns::Fence)
                    .from_col(Columns::Attempt)
                    .to_tbl(Tables::KnowledgeLeaseAcquisitions)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id)
                    .to_col(Columns::Fence)
                    .to_col(Columns::Attempt)
                    .on_delete(ForeignKeyAction::Cascade),
            )
            .foreign_key(
                ForeignKey::create()
                    .from_tbl(Tables::KnowledgeImpactConeAttempts)
                    .from_col(Columns::ProjectId)
                    .from_col(Columns::ImpactConeId)
                    .to_tbl(Tables::KnowledgeImpactCones)
                    .to_col(Columns::ProjectId)
                    .to_col(Columns::Id),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::Id))]),
                )
                .eq(36)
                .and(Expr::col(Columns::Id).eq(Expr::expr(Func::lower(Expr::col(Columns::Id))))),
            )
            .check(
                Expr::col(Columns::Fence)
                    .gt(0)
                    .and(Expr::col(Columns::Attempt).gt(0)),
            )
            .check(Expr::col(Columns::State).is_in([
                Expr::val("pending"),
                Expr::val("completed"),
                Expr::val("reused"),
                Expr::val("failed"),
                Expr::val("cancelled"),
            ]))
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::SemanticSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::SemanticSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::SemanticSha256)))),
                ),
            )
            .check(
                Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::InputSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::InputSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::InputSha256)))),
                ),
            )
            .check(Expr::col(Columns::SemanticSha256).eq(Expr::col(Columns::InputSha256)))
            .check(
                Expr::col(Columns::ErrorSha256).is_null().or(Expr::expr(
                    Func::cust(Alias::new("length"))
                        .args([SimpleExpr::from(Expr::col(Columns::ErrorSha256))]),
                )
                .eq(64)
                .and(
                    Expr::col(Columns::ErrorSha256)
                        .eq(Expr::expr(Func::lower(Expr::col(Columns::ErrorSha256)))),
                )),
            )
            .check(
                Expr::col(Columns::State)
                    .eq("pending")
                    .and(Expr::col(Columns::ImpactConeId).is_null())
                    .and(Expr::col(Columns::ErrorJson).is_null())
                    .and(Expr::col(Columns::FinishedAt).is_null())
                    .or(Expr::col(Columns::State)
                        .is_in([Expr::val("completed"), Expr::val("reused")])
                        .and(Expr::expr(Expr::col(Columns::ImpactConeId).is_null()).not())
                        .and(Expr::col(Columns::ErrorJson).is_null())
                        .and(Expr::expr(Expr::col(Columns::FinishedAt).is_null()).not()))
                    .or(Expr::col(Columns::State)
                        .is_in([Expr::val("failed"), Expr::val("cancelled")])
                        .and(Expr::col(Columns::ImpactConeId).is_null())
                        .and(Expr::col(Columns::ErrorSchemaVersion).eq(1))
                        .and(Expr::expr(Expr::col(Columns::ErrorJson).is_null()).not())
                        .and(Expr::expr(Expr::col(Columns::ErrorSha256).is_null()).not())
                        .and(Expr::expr(Expr::col(Columns::FinishedAt).is_null()).not())),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::Id),
            )
            .index(
                Index::create()
                    .unique()
                    .col(Columns::ProjectId)
                    .col(Columns::AcquisitionId)
                    .col(Columns::SemanticSha256),
            )
            .to_owned(),
    ]
}

#[derive(DeriveIden)]
enum Tables {
    KnowledgeComputationOutputs,
    KnowledgeCycleShards,
    KnowledgeCycles,
    KnowledgeExternalArtifacts,
    KnowledgeImpactConeAttempts,
    KnowledgeImpactCones,
    KnowledgeInventoryAttempts,
    KnowledgeInventoryManifests,
    KnowledgeLeaseAcquisitions,
    KnowledgeSourceSnapshots,
    Projects,
}

#[derive(DeriveIden)]
enum Columns {
    AccountedCount,
    AcquisitionId,
    ArtifactId,
    ArtifactSchemaVersion,
    ArtifactSha256,
    Attempt,
    ComputationOutputId,
    ContradictionCount,
    CreatedAt,
    CycleId,
    EligibleCount,
    ErrorJson,
    ErrorSchemaVersion,
    ErrorSha256,
    Fence,
    FinishedAt,
    GraphSha256,
    Id,
    ImpactConeId,
    IncludedCount,
    InputSha256,
    InventoryId,
    KnowledgeRevision,
    KnowledgeViewSha256,
    OutputSha256,
    ProjectId,
    ResultSha256,
    SemanticSchemaVersion,
    SemanticSha256,
    Sha256,
    ShardId,
    SourceSnapshotId,
    State,
    StoreUuid,
    UninitializedKnowledgeSha256,
    UnownedCount,
    VerifiedAt,
}

#[cfg(test)]
mod tests {
    use super::*;
    use assertr::prelude::*;

    fn normalize(sql: &str) -> String {
        sql.chars()
            .filter(|c| !c.is_whitespace() && *c != '"')
            .flat_map(char::to_uppercase)
            .collect()
    }

    #[test]
    fn inventory_impact_tables_are_ordered_and_postgres_portable() {
        let sql = knowledge_inventory_impact_tables()
            .iter()
            .map(|table| normalize(&table.to_string(PostgresQueryBuilder)))
            .collect::<Vec<_>>();
        assert_that!(&sql.len()).is_equal_to(4);
        for (index, table) in [
            "knowledge_inventory_manifests",
            "knowledge_impact_cones",
            "knowledge_inventory_attempts",
            "knowledge_impact_cone_attempts",
        ]
        .into_iter()
        .enumerate()
        {
            assert_that!(&sql[index])
                .contains(normalize(&format!("CREATE TABLE IF NOT EXISTS {table}")));
            assert_that!(&sql[index]).does_not_contain(normalize("AUTOINCREMENT"));
            assert_that!(&sql[index]).does_not_contain(normalize("CREATE TRIGGER"));
        }
        assert_that!(&sql[0]).contains(normalize(
            "REFERENCES knowledge_source_snapshots(project_id, id)",
        ));
        assert_that!(&sql[0]).contains(normalize("REFERENCES knowledge_computation_outputs(project_id, id, cycle_id, shard_id, acquisition_id, fence, output_sha256)"));
        assert_that!(&sql[0]).does_not_contain(normalize("result_json"));
        assert_that!(&sql[0]).does_not_contain(normalize("input_json"));
        assert_that!(&sql[0]).contains(normalize("artifact_schema_version"));
        assert_that!(&sql[1]).contains(normalize(
            "REFERENCES knowledge_inventory_manifests(project_id, id)",
        ));
        assert_that!(&sql[1]).does_not_contain(normalize("result_json"));
        assert_that!(&sql[1]).contains(normalize(
            "FOREIGN KEY (project_id, acquisition_id, fence, attempt)",
        ));
        assert_that!(&sql[2]).contains(normalize(
            "REFERENCES knowledge_lease_acquisitions(project_id, id, fence, attempt)",
        ));
        assert_that!(&sql[3]).contains(normalize(
            "REFERENCES knowledge_impact_cones(project_id, id)",
        ));
    }
}
