mod api_docs;
mod automation;
mod board;
mod codex;
mod error;
mod item;
mod not_found;
mod projects;
mod run_log;
mod runs;

pub use api_docs::{ApiDocsPage, PageApiDocs};
pub use automation::{AutomationRuleInspectorView, PageTriggers, TriggersPage};
pub(crate) use board::memory_event_ref_label;
pub use board::{BoardItemsSection, BoardPage, PageBoard};
pub(crate) use codex::format_number;
pub use codex::{CodexStatusPage, PageCodex};
pub use error::PageError;
pub(crate) use item::infer_dispatch_run_id;
pub use item::{ItemPage, PageItem};
pub use not_found::PageErr404;
pub use projects::{PageProjects, ProjectsPage};
pub use run_log::{PageRunLog, RunLogPage};
pub use runs::{BoardRunSessionView, PageRuns, RunsPage, RunsSection};
