mod api_docs;
mod automation;
mod board;
mod codex;
mod error;
mod item;
mod knowledge;
mod metrics;
mod not_found;
mod project;
mod projects;
mod run_log;
mod runs;

pub use api_docs::PageApiDocs;
pub use automation::PageTriggers;
pub use board::PageBoard;
pub use codex::PageSystem;
pub(crate) use codex::format_number;
pub use error::PageError;
pub(crate) use item::ItemDetailContent;
pub use item::PageItem;
pub(crate) use item::infer_dispatch_run_id;
pub use knowledge::PageKnowledge;
pub use metrics::PageMetrics;
pub use not_found::PageErr404;
pub use project::PageProject;
pub use projects::PageProjects;
pub use run_log::PageRunLog;
pub(crate) use run_log::RunLogContent;
pub use runs::PageRuns;
