mod api_docs;
mod automation;
mod board;
mod codex;
mod error;
mod item;
mod knowledge;
mod metrics;
mod not_found;
mod project;
mod projects;
mod run_log;
mod runs;

pub use api_docs::{ApiDocsPage, PageApiDocs};
pub use automation::{AutomationRuleInspectorView, PageTriggers, TriggersPage};
pub use board::{BoardItemView, BoardItemsSection, BoardPage, BoardRunPreview, PageBoard};
pub(crate) use codex::format_number;
pub use codex::{CodexStatusPage, PageSystem};
pub use error::PageError;
pub(crate) use item::ItemDetailContent;
pub(crate) use item::infer_dispatch_run_id;
pub use item::{ItemPage, PageItem};
pub use knowledge::PageKnowledge;
pub use metrics::{MetricsPageData, PageMetrics};
pub use not_found::PageErr404;
pub use project::{PageProject, ProjectPage, WorkspaceBarData};
pub use projects::{PageProjects, ProjectsPage};
pub(crate) use run_log::RunLogContent;
pub use run_log::{PageRunLog, RunLogPage};
pub use runs::{PageRuns, RunSummaryView, RunsSection};
